name: Build and Deploy 

on:
  push:
    branches:
      - www

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install TexLive
        run: sudo apt install texlive-xetex texlive-latex-extra texlive-fonts-extra texlive-lang-chinese
      - name: Checkout
        uses: actions/checkout@master
        with:
          sparse-checkout: |
            template.tex
            phyreport.cls

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: www
          path: www
          sparse-checkout: |
            index.html
            物理实验模板.doc
      
      - name: Build
        run: xelatex ./template.tex && mv ./template.pdf www/

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: www
