name: Build and Deploy 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install TexLive
        run: sudo apt install texlive-full

      - name: Checkout
        uses: actions/checkout@master
        with:
          sparse-checkout: |
            template.tex
            phyreport.cls
          persist-credentials: false

      - name: Build
        run: |
          xelatex ./template.tex
          mkdir example && mv *.pdf ./example/

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./example
